### ISSUE TITLE
Restrict users from changing their votes

### ISSUE THREAD

**Issue by dsevillamartin** [FriendsOfFlarum/polls#1]
> An option per poll to restrict changing votes after a user has voted could be useful.
> 
> — https://github.com/ReFlar/polls/issues/41

**Comment by Eldenroot** [comment]
@dsevillamartin - would be nice to see this feature too with your rewritting :)

This should be a checkbox when you adding a poll.

**Comment by dsevillamartin** [comment]
This has been added in 2.1.0
