### ISSUE TITLE
You don't have permission to vote

### ISSUE THREAD

**Issue by bcashier** [FriendsOfFlarum/polls#14]
Hi,

I installed POLL extension but it seem not working in the user side ... they are unable to vote !

And normal users also are unable to create a poll, only admin allowed !

Thank you

**Comment by datitisev** [comment]
What are your reacting permissions set to?

**Comment by bcashier** [comment]
@datitisev Thanks for your answer !

I can't find where I can set permissions !

I just installed it, and then enabled it.

**Comment by datitisev** [comment]
In the permissions page; they should be there.

![image](https://user-images.githubusercontent.com/6401250/82762585-d543c180-9dcf-11ea-930a-91d16d591bec.png)

![image](https://user-images.githubusercontent.com/6401250/82762587-db39a280-9dcf-11ea-9a81-2277682204e5.png)

**Comment by bcashier** [comment]
Awesome !

Last thing please, non registered users can't see the percent of votes (stats), is it normal ?

Thank you

**Comment by datitisev** [comment]
Just realized I pointed you to fof/reactions permissions instead of fof/polls - looks like you were able to find them anyway, sorry about that.

I think the % of votes can only be seen once you vote or the poll has expired. I can't exactly remember.

**Comment by bcashier** [comment]
@datitisev Oh ok I see !

So, for polls without expirations, users will be unable to see the stats :(

Yes when you you vote, you will be able to see the number of voters.

**Comment by datitisev** [comment]
I think so, yes.

**Comment by bcashier** [comment]
Thank you sir ! I appreciate your help !

**Comment by datitisev** [comment]
No problem!

**Comment by bcashier** [comment]
@datitisev Please, is there a patch or something to show the stats for anonymous users ?

Something like if(!$user) { show stats }  else { show normal poll }

??

Thanks

**Comment by datitisev** [comment]
You can't currently do anything about it. That will have to be added to the extension.

**Comment by bcashier** [comment]
@datitisev Thank you again :)
