### ISSUE TITLE
Hide votes in poll until poll expires

### ISSUE THREAD

**Issue by dsevillamartin** [FriendsOfFlarum/polls#2]
> https://discuss.flarum.org/d/9762-poll/74
> 
> — https://github.com/ReFlar/polls/issues/39

**Comment by cmwetherell** [comment]
This would be a good feature.

**Comment by Eldenroot** [comment]
@dsevillamartin - would be nice to see this feature too with your rewritting :)

This should be a checkbox when you adding a poll.
