### ISSUE TITLE
Poll end date panel broken

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [FriendsOfFlarum/polls#27]
https://i.imgur.com/ot6zzze.jpg
Web browser: firefox
Flarum: latest

The list of months doesn't open. Some month names are slightly cropped at the bottom. The year numbers are slightly cropped at the bottom. I can't add a calendar translation to other languages.

**Comment by Ralkage** [comment]
Hi @Envel-Nikita-Gutsenkov and sorry for the extremely late reply! We are deciding whether or not to use the native date picket supported by browsers in place of the package we are using for our datepicker for this feature. If you are still having this issue, even in the latest version of Polls, please bear with us while we reach a decision collectively on this possible change.

**Comment by dsevillamartin** [comment]
Fixed in #72
