### ISSUE TITLE
Select one or multiple options per poll

### ISSUE THREAD

**Issue by dsevillamartin** [FriendsOfFlarum/polls#3]
> allow multiple/or only one vote per poll (if multiple selected, add posibility to set how much votes the user has - for example can choose up to 3 options from 10).
> 
> — https://github.com/ReFlar/polls/issues/29

**Comment by bodagrave** [comment]
That one really would be helpful. I would love it to be able to define how many polls one user has while starting a new poll.
As soon as the first user picked his choices, there should be no possibility to change the amount of choices or the typ (single choice / multi choice). This would prevent logical issues if one user picked more choices than should be allowed when changed again.

**Comment by Tophicles** [comment]
I agree, having the ability to select multiple answers would be a great feature.
The first poll I created I had assumed you could do this, oops! lol

**Comment by cnachtigall1991** [comment]
is there any update to this?
