### ISSUE TITLE
Drop reflar database compatibility

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/polls#37]
The migrations include special conditions for migrating the old reflar/polls table. This includes codes we must continue to maintain.

Those can be dropped. If anyone still requires them, they can just install an older version of fof/polls to perform the migration.

I suggest we remove that additional code, as well as the `FoF\Polls\Migrations\AbstractMigration` class and just use normal migrations. We can keep the same file names so nothing will break for anyone.

**Comment by dsevillamartin** [comment]
Fixed in #74
