### ISSUE TITLE
Plugin seems to load "flatpickr.min.css" from external CDN

### ISSUE THREAD

**Issue by poVoq** [FriendsOfFlarum/polls#44]
## Bug Report

**Current Behavior**
Plugin works fine but causes problems (both legal and technical) in environments that strictly prohibit loading external resources. Furthermore the CDN is hosted by Cloudflare with is a privacy concern.

As this seems to be only a small css file, would it be possible to just include it in the distribution instead of downloading it?

Thanks.

**Comment by rafaucau** [comment]
By the way, this extension could use the native HTML picker instead of the library.

**Comment by n0099** [comment]
Due to service downgrade of jsdelivr in mainland china: https://github.com/jsdelivr/jsdelivr/issues/18348#issuecomment-997777996, it's now more important to allow user self-host this css instead of requesting from public cdn which is currently unstable in china.

**Comment by imorland** [comment]
This is quite easy to solve, I'll sort this shortly...
