### ISSUE TITLE
Incompatibility with kyrne/websockets

### ISSUE THREAD

**Issue by wonderbeel** [FriendsOfFlarum/polls#46]
## Bug Report

**Current Behavior**
There seems to be an incompatibility with the websockets extension, I suspect that it is because it uses the `pusher` name but the object is slightly different from the one that is returned by the pusher extension. 

**Steps to Reproduce**
1. Install and enable both `fof/polls` and `kyrne/websockets`
2. Configure `kyrne/websockets`
3. Open a discussion and go in the console

**Expected Behavior**
 Discussion posts should update live when fof/polls is enabled and there should be no console errors

**Screenshots**
https://i.imgur.com/VL7oIRw.png

**Environment**
- Flarum version: 1.0.4
- Extension version: 10.3
- Website URL: https://off-popic.it
- Webserver: nginx
- Hosting environment: vps
- PHP version: 7.4
- Browser: Firefox 90

**Additional Context**
Not sure if it is a bug for you guys or if I should report it to Kyrne because if his extension isn't 100% compatible with Pusher.

**Comment by dsevillamartin** [comment]
Closing since Websockets was discontinued.
