### ISSUE TITLE
No ability to change permissions to create polls

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/polls#77]
## Bug Report

**Current Behavior**
After upgrading to version 2.0, I cannot change the permissions to create polls. All options are grayed out.
![image](https://github.com/FriendsOfFlarum/polls/assets/25438601/41add658-2c48-4a9a-8fa7-694c29b4c709)

**Environment**
- Flarum version: 1.8.1
- Extension version: 2.0.1
- PHP version: 8.2
- Browser: Chrome 115

**Comment by dsevillamartin** [comment]
@rafaucau No worries! Glad we got it figured out.
