### ISSUE TITLE
Allow inline polls on all posts

### ISSUE THREAD

**Issue by boston2029** [FriendsOfFlarum/polls#89]
## Feature Request
Please make it so you can insert a poll anywhere in any post, rather than a topic. And it should work in an edit as well.
**Is your feature request related to a problem? Please describe.**
I wanted to add a poll to a post after finding the FoF Polls extension, but couldn't without reposting.
**Describe alternatives you've considered**
Using FoF Gamification for voting, or delete topic and make new one with the poll in it.

**Comment by dsevillamartin** [comment]
This is possible since v2 released in July, I believe?
